get:
  tags:
    - VAA
  summary: Fetches all theses for one VAA
  operationId: getThesesForApplication
  parameters:
    - in: path
      name: applicationId
      required: true
      schema:
        type: integer
        format: int64
      description: Numeric ID of the VAA
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            oneOf:
              - type: array
                items:
                  type: object
                  $ref: schemas/These.yaml#/These
              - type: array
                items:
                  type: object
                  $ref: schemas/These.yaml#/LanguageThese
post:
  tags:
    - VAA
  summary: Add these
  operationId: createTheseForApplication
  parameters:
    - in: path
      name: applicationId
      required: true
      schema:
        type: integer
        format: int64
      description: Numeric ID of the VAA
  requestBody:
    content:
      application/json:
        schema:
          $ref: schemas/These.yaml#/LanguageThese
  responses:
    '201':
      description: Success
      content:
        application/json:
          schema:
            $ref: schemas/These.yaml#/These
put:
  tags:
    - VAA
  summary: Put these
  operationId: putThesesForApplication
  parameters:
    - in: path
      name: applicationId
      required: true
      schema:
        type: integer
        format: int64
      description: Numeric ID of the VAA
  requestBody:
    content:
      application/json:
        schema:
          $ref: schemas/These.yaml#/LanguageThese
  responses:
    '201':
      description: Success
      content:
        application/json:
          schema:
            $ref: schemas/These.yaml#/These
delete:
  tags:
    - VAA
  summary: Delete VAA object
  operationId: deleteThesesForApplication
  parameters:
    - in: path
      name: applicationId
      required: true
      schema:
        type: integer
        format: int64
      description: Numeric ID of the VAA
  responses:
    '201':
      description: Success
