get:
  tags:
    - VAA
  summary: Fetches array of VAA's
  operationId: getApplications
  parameters:
    - name: launch_date
      in: query
      description: Launch date of VAA
      schema:
        type: string
        format: date
        example: '2021-10-01'
    - name: sundown_date
      in: query
      description: Sundown date of VAA
      schema:
        type: string
        format: date
        example: '2021-10-01'
    - name: limit
      in: query
      description: Limits the amount of items in the responsing array. Max results is 50.
      schema:
        type: integer
        example: 20
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              $ref: schemas/Application.yaml#/Application
post:
  tags:
    - VAA
  summary: Create VAA object
  operationId: createApplication
  requestBody:
    content:
      application/json:
        schema:
          $ref: schemas/Application.yaml#/NewApplication
  responses:
    '201':
      description: Success
      content:
        application/json:
          schema:
            $ref: schemas/Application.yaml#/Application
      links:
        GetApplicationById:
          operationId: getApplication
          parameters:
            electionId: $response.body#/id
          description: >
            The `id` value returned in the response can be used as the
            **applicationId** parameter in `GET /applications/{applicationId}`.
