get:
  tags:
    - Vote
  summary: Get existing vote
  operationId: getVotingForApplication
  parameters:
    - in: path
      name: applicationId
      required: true
      schema:
        type: integer
        format: int64
      description: Numeric ID of the VAA
    - in: path
      name: voteId
      required: true
      schema:
        type: integer
        format: int64
      description: Numeric ID of the vote
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: schemas/Voting.yaml#/Voting
