post:
  tags:
    - Vote
  summary: Submit a new voting for an VAA
  operationId: createVotingForApplication
  parameters:
    - in: path
      name: applicationId
      required: true
      schema:
        type: integer
        format: int64
      description: Numeric ID of the VAA
  requestBody:
    content:
      application/json:
        schema:
          $ref: schemas/Voting.yaml#/NewVoting
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: schemas/Voting.yaml#/Voting
      links:
        GetVoteById:
          operationId: getVotingForApplication
          parameters:
            voteId: $response.body#/id
            applicationId: $response.body#/application_id
          description: >
            The `id` value returned in the response can be used as the
            **voteId** parameter in `GET
            /applications/{applicationId}/votings/{voteId}`.


            The `application_id` value returned in the response can be used as
            the **applicationId** parameter in `GET
            /applications/{applicationId}/votings/{voteId}`.
