openapi: 3.0.0
info:
  title: OPEN VOTE ADVICE APPLICATION API
  description: Defines a common interface for vote advice applications.
  version: 0.0.1
  contact:
    name: API Support
    url: 'https://voto.vote/'
    email: help@voto.vote
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://{environment}.voto.vote/{version}'
    description: VOTO API Endpoint
    variables:
      environment:
        default: api
        enum:
          - api
          - dev.api
      version:
        default: v1
        enum:
          - v1
          - v2
tags:
  - name: Election
    description: Objects related to elections.
  - name: VAA
    description: Objects related to Vote advice applications.
  - name: API
    description: About this API
  - name: Vote
    description: Endpoints for everything vote related
paths:
  /:
    $ref: paths.yaml
  /elections:
    $ref: paths/elections.yaml
  '/elections/{electionId}':
    $ref: 'paths/elections@{electionId}.yaml'
  '/elections/{electionId}/candidates':
    $ref: 'paths/elections@{electionId}@candidates.yaml'
  '/elections/{electionId}/candidates/{candidateId}':
    $ref: 'paths/elections@{electionId}@candidates@{candidateId}.yaml'
  '/elections/{electionId}/candidates/{candidateId}/votes':
    $ref: 'paths/elections@{electionId}@candidates@{candidateId}@votes.yaml'
  '/elections/{electionId}/parties':
    $ref: 'paths/elections@{electionId}@parties.yaml'
  '/elections/{electionId}/parties/{partyId}':
    $ref: 'paths/elections@{electionId}@parties@{partyId}.yaml'
  '/elections/{electionId}/parties/{partyId}/votes':
    $ref: 'paths/elections@{electionId}@parties@{partyId}@votes.yaml'
  /applications:
    $ref: paths/applications.yaml
  '/applications/{applicationId}':
    $ref: 'paths/applications@{applicationId}.yaml'
  '/applications/{applicationId}/metadata':
    $ref: 'paths/applications@{applicationId}@metadata.yaml'
  '/applications/{applicationId}/theses':
    $ref: 'paths/applications@{applicationId}@theses.yaml'
  '/applications/{applicationId}/votings':
    $ref: 'paths/applications@{applicationId}@votings.yaml'
  '/applications/{applicationId}/votings/{voteId}':
    $ref: 'paths/applications@{applicationId}@votings@{voteId}.yaml'
