ActionRequest: 
  type: object
  properties:
    action: 
      type: string
      enum: [FinalizeAppTheses, FinalizePartyTheses,FinalizeCandidateTheses,CandidateFirstLogin]
    id:
      type: integer
      example: 123
      description: Must be the applicationId/partyId


MailOptions: 
  type: object
  properties: 
    formats:
      type: string
      description: "comma separated list of mail formats. Can be 'html' and/or 'plain'"


InviteRequest: 
  type: object
  properties: 
    id:
      type: integer
      example: 123
      description: Must be the candidate/trustperson/creator/admin ID
    Mailoptions:
      type: object
      $ref: "Action.yaml#/MailOptions"