ActionRequest: 
  type: object
  properties:
    action: 
      type: string
      enum: [ActionTypeChangeMail, ActionTypeChangePassword, ActionFinalizeAppTheses, ActionFinalizePartyTheses, ActionFinalizeCandidateTheses, ActionCandidateFirstLogin]
    id:
      type: integer
      example: 123
      description: Must be the applicationId/partyId


MailOptions: 
  type: object
  properties: 
    formats:
      type: string
      description: "comma separated list of mail formats. Can be 'html' and/or 'plain'"


InviteRequest: 
  type: object
  properties: 
    id:
      type: integer
      example: 123
      description: Must be the candidate/trustperson/creator/admin ID
    Mailoptions:
      type: object
      $ref: "Action.yaml#/MailOptions"

TheseDeviation: 
  type: object
  properties: 
    Value:
      type: float
      example: 12.2
    StatementId:
      type: integer
      example: 123
      description: ID of the statement
    Votes:
      type: integer
      example: 123
      description: Number of votes used for the calculation

StdDeviationAnalysis:
  type: object
  properties:
    Candidates:
      type: array
      items:
        type: object
        $ref: "Action.yaml#/TheseDeviation"
    Parties:
      type: array
      items:
        type: object
        $ref: "Action.yaml#/TheseDeviation"