ActionRequest: 
  type: object
  properties: 
    action: 
      type: string
      enum: [FinalizeAppTheses, FinalizePartyTheses, InviteCandidate, InviteTrustperson]
    value:
      type: array
      items:
        type: integer
        example: 1
        description: This is the ID of the application and based on the request also ID of party/candidate