Application:
  allOf:
    - $ref: "Application.yaml#/NewApplication"
    - type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 123
        created_at:
          type: string
          format: date-time
          example: 2021-10-05T06:00:00Z
        updated_at:
          type: string
          format: date-time
          example: 2021-10-05T06:00:00Z

Applications: 
  type: object
  properties: 
    data: 
      type: array
      items:
        type: object
        $ref: "Application.yaml#/Application"
    pagination:
      $ref: "Pagination.yaml#/Pagination"

NewApplication:
  type: object
  required:
    - election_id
    - cluster_id
    - title
  properties:
    election_id:
      type: integer
      example: 123
    cluster_id:
      type: integer
      example: 456
    theme_id:
      type: integer
      example: 789
    title:
      type: string
      example: "Example Title"
    subtitle:
      type: string
      example: "Example Subtitle"
    description:
      type: string
      example: "Lorem ipsum dolor sed amet."
    website:
      type: string
      example: "https://voto.vote"
    url:
      type: string
      example: "https://foo.bar/vaa"
    launch_date:
      type: string
      format: date
      example: "2021-08-27"
    sundown_date:
      type: string
      format: date
      example: "2021-09-27"
    configuration:
      type: string
      example: "https://voto.vote/foo_bar.json"
      description: "This is the url, where you find your individual configuration for the VOTO VAA"
    status:
      type: integer
      example: 123

DeleteApplication:
  type: object
  required:
    - id
  properties:
    id:
      type: integer
      format: int64
      example: 123
