name: deploy-github-page
on:
  push:
    branches: [main, dev]
jobs:
  test_job:
    runs-on: self-hosted
    name: Deploy redoc on github page
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate redoc
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: "bundle openapi/specification.yaml -o docs/index.html"
